print("Welcome to the tip calculator!")
bill = float(input("What was the total bill?:    $"))
tip = int(input("What percentage tip would you like to give? ie: 10 12 15 20:  "))
people = int(input("How many people to split the bill?:  "))
tip_pct = float(tip/100)
bill_w_tip = round(bill * (1+tip/100),2)
bill_w_tip_f = "{:.2f}".format(bill_w_tip)
print(f"Total Bil + Tip:   ${bill_w_tip_f}")
bill_share = round(bill_w_tip / people, 2)
bill_share_f = "{:.2f}".format(bill_share)
print(f"Each person should pay:   ${bill_share_f}")
